-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 15:36:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `course_no` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `credits` INT NULL,
  `Syllabus` VARCHAR(255) NULL,
  `prerequisites` VARCHAR(45) NULL,
  `Course_course_no` INT NOT NULL,
  `Course_course_no1` INT NOT NULL,
  `Course_course_no2` INT NOT NULL,
  PRIMARY KEY (`course_no`, `Course_course_no2`),
  INDEX `fk_Course_Course1_idx` (`Course_course_no` ASC) VISIBLE,
  INDEX `fk_Course_Course2_idx` (`Course_course_no2` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Course1`
    FOREIGN KEY (`Course_course_no`)
    REFERENCES `mydb`.`Course` (`course_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Course2`
    FOREIGN KEY (`Course_course_no2`)
    REFERENCES `mydb`.`Course` (`course_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instructor` (
  `instructor_id` INT NOT NULL,
  `name` VARCHAR(245) NULL,
  `department` VARCHAR(245) NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`instructor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courseOffering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courseOffering` (
  `offering_id` INT NOT NULL AUTO_INCREMENT,
  `course_no` INT NULL,
  `year` INT NULL,
  `semester` INT NULL,
  `section_no` INT NULL,
  `instructor_id` INT NULL,
  `timings` VARCHAR(45) NULL,
  `classroom` VARCHAR(45) NULL,
  PRIMARY KEY (`offering_id`),
  INDEX `fk_courseOffering_1_idx` (`instructor_id` ASC) VISIBLE,
  INDEX `fk_courseOffering_2_idx` (`course_no` ASC) VISIBLE,
  CONSTRAINT `fk_courseOffering_1`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `mydb`.`instructor` (`instructor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courseOffering_2`
    FOREIGN KEY (`course_no`)
    REFERENCES `mydb`.`Course` (`course_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `student_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `program` VARCHAR(255) NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enrollement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enrollement` (
  `enrollement_id` INT NOT NULL,
  `student_id` INT NULL,
  `offering_id` INT NULL,
  `grade` VARCHAR(45) NULL,
  PRIMARY KEY (`enrollement_id`),
  INDEX `fk_Enrollement_1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_Enrollement_2_idx` (`offering_id` ASC) VISIBLE,
  CONSTRAINT `fk_Enrollement_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enrollement_2`
    FOREIGN KEY (`offering_id`)
    REFERENCES `mydb`.`courseOffering` (`offering_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
